
server:
  port: 8088
location: C:/JavaEE/Apache Software Foundation8.5/Tomcat 8.5/webapps/schooldelivery-system/src/main/resources/static/images/productimg
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: Joanne1428
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      min-idle: 5
      max-active: 10
      max-wait: 3000
  thymeleaf:
    prefix: classpath:/templates/water/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
  http:
    multipart:
      enabled: true
  web:
    resources:
      static-locations: classpath:/static/,classpath:/static/assets/,classpath:/public/,classpath:/resources/,classpath:/META-INF/resource/,file:${location}
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
pagehelper:
  helper-dialect: mysql
upload:
  path: /export/home/
